---
- name: Install Apache and Clone Ecomm Repo
  hosts: n1
  become: yes

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Start Apache
      service:
        name: apache2
        state: started
      when: ansible_distribution == 'Ubuntu'

    - name: Enable Apache
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install Git
      apt:
        name: git
        state: present
      when: ansible_distribution == 'Ubuntu'
   
    - name: Clone Ecomm Repo
      git:
        repo: https://github.com/CeeyIT-Solutions/ecomm-3.git
        dest: /var/www/html
        become: yes
        force: yes
      when: ansible_distribution == 'Ubuntu'
...
